/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engine.view;

import engine.system.SystemLib;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JComponent;
import space.base.BaseEngine;
import space.view.HandlerDragged;
import space.view.JFileChooserView;
import space.view.table.jTabbedPaneView;

/**
 *
 * @author 35191
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        load();
        SystemLib.load();
        ArrayList<JComponent> components =new ArrayList<>();
        components.add(paneMan);
        new HandlerDragged(BTeste,components);
    }
    
    
    private void load(){
        itemMenuAddLib.addActionListener(l -> {
            System.out.println("ADD LIB");
        });
        
        BaseEngine.setMenu(menuMan);
        BaseEngine.setProject(treeProjects);
        BaseEngine.setResource(treeResoucer);
        BaseEngine.setPaneMain((jTabbedPaneView) paneMan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new jTabbedPaneView();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeProjects = new javax.swing.JTree();
        jTabbedPane2 = new jTabbedPaneView();
        jScrollPane3 = new javax.swing.JScrollPane();
        treeResoucer = new javax.swing.JTree();
        jTabbedPane4 = new jTabbedPaneView();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paneMan = new jTabbedPaneView();
        BTeste = new javax.swing.JButton();
        menuMan = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemMenuAddLib = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFocusable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeProjects.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(treeProjects);

        jTabbedPane1.addTab("Projects", jScrollPane2);

        jTabbedPane2.setFocusable(false);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeResoucer.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(treeResoucer);

        jTabbedPane2.addTab("Resoucer", jScrollPane3);

        jTabbedPane4.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Properties", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Palette", jPanel2);

        BTeste.setText("jButton1");
        BTeste.setFocusable(false);

        jMenu1.setText("File");

        itemMenuAddLib.setText("Add Lib");
        itemMenuAddLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAddLibActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuAddLib);

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        menuMan.add(jMenu1);

        setJMenuBar(menuMan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneMan, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BTeste)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane4)
                    .addComponent(paneMan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuAddLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAddLibActionPerformed
     
        
       File[] files = JFileChooserView.getFiles("Select an lib", "C:\\Users\\35191\\Documents\\NetBeansProjects\\ExpoLib", JFileChooserView.creadFilter("Lib jar", "jar"));

       if(files!=null){ 
            for(File file : files){
             SystemLib.addLib(file).install();
            }
            BaseEngine.reloadView();
       }

    }//GEN-LAST:event_itemMenuAddLibActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTeste;
    private javax.swing.JMenuItem itemMenuAddLib;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JMenuBar menuMan;
    private javax.swing.JTabbedPane paneMan;
    private javax.swing.JTree treeProjects;
    private javax.swing.JTree treeResoucer;
    // End of variables declaration//GEN-END:variables
}